### ISSUE TITLE
Script Missing

### ISSUE THREAD

**Issue by Timor666** [JiangJie/flexbox4unity#1]
看好你
Git上好像只有你一个
是FlexBox For Unity UGUI的 哈哈

将Preafb拉到场景中后，显示脚本丢失。
老哥是不是没有将.meta文件推送上来呢？

![image](https://github.com/JiangJie/flexbox4unity/assets/35324214/889a438c-c010-4061-bf38-e99945132c00)

**Comment by JiangJie** [comment]
多谢提醒，已上传，祝使用愉快！
